# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-test

on:
  pull_request:
    branches: [main]

jobs:
  ci-test:
    # NOTE: This name appears in GitHub's Checks API.
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
